import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UsersProvider } from "./contexts/users.context";
import { CategoriesProvider } from "./contexts/categories.context";
import { EntriesProvider } from "./contexts/entries.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<UsersProvider>
			<CategoriesProvider>
				<EntriesProvider>
					<html lang="en">
						<body className={inter.className}>{children}</body>
					</html>
				</EntriesProvider>
			</CategoriesProvider>
		</UsersProvider>
	);
}
